### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by obliviux** [honcheng/PaperFoldMenuController#1]
A lot of files are missing in the PaperFold folder 
http://cl.ly/image/1m2r1D1C2a3W
Thanks and great work anyway!

**Comment by honcheng** [comment]
Hi, 
Those files are from a separate git repository, added as submodule. You have to init & update submodule to pull the files.

**Comment by obliviux** [comment]
Thanks, but now I get some errors:
http://cl.ly/image/3f3H392O0q3f
Thank you

**Comment by honcheng** [comment]
did you pull it automatically from the submodule, or did you download it manually from the paperfold? 
I pulled it automatically and it works fine. 

If you get those errors, you are probably in the wrong paperfold branch. Try to checkout the 'top-multifold' branch and it'll work. 

Or just use the SourceTree app, and it pulls the submodule for you automatically.

**Comment by obliviux** [comment]
I managed to get it working with SourceTree! Thank you for your support and your great work!
