### ISSUE TITLE
No setEnableHorizontalEdgeDragging method on PaperFoldView

### ISSUE THREAD

**Issue by andriyadi** [honcheng/PaperFoldMenuController#5]
As title.

So this method in PaperFoldMenuController is failed:

``` objective-c
- (void)setOnlyAllowEdgeDrag:(BOOL)onlyAllowEdgeDrag
{
    [self.paperFoldView setEnableHorizontalEdgeDragging:onlyAllowEdgeDrag];
}
```

Please advice. I have to comment the body to make the project works.

**Comment by honcheng** [comment]
Hi Andri,

You have to pull the latest update for PaperFold. That is a submodule

**Comment by andriyadi** [comment]
Confirmed! Just update the submodule. Thanks!

**Comment by honcheng** [comment]
Thanks
