### ISSUE TITLE
Create tags for CocoaPods integration

### ISSUE THREAD

**Issue by texastoland** [honcheng/PaperFoldMenuController#9]
I plan to push a [podspec](https://gist.github.com/4265020#file-paperfoldmenucontroller-podspec) but updates require tags; see [Unversioned Libraries](https://github.com/CocoaPods/CocoaPods/wiki/Contributing-to-the-master-repo). The matching PaperFold version will need tagged too. I used your Nov 22 commits.

**Comment by honcheng** [comment]
It's done. Thanks.

**Comment by texastoland** [comment]
You're welcome. Each tag also needs PaperFold to be tagged at its submodule version to be complete.
